<a href="https://colab.research.google.com/github/mayankraj25/PyTorch/blob/main/Pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
#Number(float)
t1=torch.tensor(4.)
print(t1)

#Vector
t2=torch.tensor([1.,2,3,4]) #Tensor just stors a single type of datatype hence all of it turns to float
print(t2)

#Matrix
t3=torch.tensor([[5.,6],[7,8],[9,10]])
print(t3)

#3D Array
t4=torch.tensor([[[11,12,13],[13,14,15]],[[15,16,17],[17,18,19]]])
print(t4)

tensor(4.)
tensor([1., 2., 3., 4.])
tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])


In [3]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.float32
torch.float32
torch.int64


In [4]:
print(t1)
print(t1.shape)
print(t2)
print(t2.shape)
print(t3)
print(t3.shape)
print(t4)
print(t4.shape)

tensor(4.)
torch.Size([])
tensor([1., 2., 3., 4.])
torch.Size([4])
tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
torch.Size([3, 2])
tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])
torch.Size([2, 2, 3])


In [5]:
#Create Tensors
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)

#Arithematic operation
y=w*x+b
print(y)

#Computing Derivative
y.backward()
#Display Gradients (Gradient is just another name for drivative)
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

tensor(17., grad_fn=<AddBackward0>)
dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [6]:
import numpy as np
x=np.array([[1,2],[3,4.]])
print(x)
print(x.dtype)
y=torch.from_numpy(x)
print(y)
print(y.dtype)
z=y.numpy()
print(z)

[[1. 2.]
 [3. 4.]]
float64
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
torch.float64
[[1. 2.]
 [3. 4.]]


In [9]:
#Linear Regression - y=w.x+b
#Where w is the weight and b is he bias
#for our example the whole equation will look like ->
#yield_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1
#yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [8]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
